[package]
name = "pillid"
version = "0.1.5"
authors = ["Aditya Pillai <github.4nsjt@simplelogin.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/pilleye/pillid"
description = "A tinier, prefixed, URL-friendly, time-sortable, unique ID storable on the stack."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
chrono = "0.4.31"
paste = "1.0.14"
rand = "0.8.5"
serde = { version = "1.0.188", features = ["derive"] }
sqlx = { version = "0.7.2", features = [
    "sqlite",
    "mysql",
    "postgres",
    "runtime-tokio",
    "tls-rustls",
    "uuid",
    "chrono",
], optional = true }
thiserror = "1.0.49"

[features]
default = []
sqlx = ["dep:sqlx"]
